export const buildStatusConfig = {
  title: 'Build Status',
  refreshIntervalSeconds: 60,
  datasource: {
    circleCI: {
      enabled: false,
      // generate token here: https://app.circleci.com/settings/user/tokens
      apiToken: process.env.CIRCLE_CI_API_TOKEN,
      // projects you want to monitor
      projects: [
        {
          projectName: 'project_name',
          projectSlug: 'gh/org_name/repo_name',
          branch: 'master',
          level: 'medium',
        },
        {
          projectName: 'project_name',
          projectSlug: 'gh/org_name/repo_name',
          branch: 'master',
          level: 'low',
        },
      ],
    },
    github: {
      enabled: true,
      // generate GitHub token with Read access to GitHub Actions, code, and metadata
      apiToken: process.env.GITHUB_API_TOKEN,
      // GitHub API url (for self-hosted GitHub, default URL is https://api.github.com)
      baseUrl: 'https://git.i.mercedes-benz.com/api/v3',
      // refresh interval for Build Status
      refreshIntervalSeconds: 60,
      // projects you want to monitor
      // workflow ID may check by https://api.github.com/repos/USER/REPO/actions/workflows
      projects: [
        {
          projectName: 'Handover Build & Deploy',
          owner: 'OTR-Germany',
          repo: 'handover',
          branch: 'main',
          workflowId: 31680,
          level: 'high',
        },
        {
          projectName: 'Invoices Build & Deploy',
          owner: 'OTR-Germany',
          repo: 'invoices-service',
          branch: 'main',
          workflowId: 70101,
          level: 'high',
        },
        {
          projectName: 'Handover PR Check',
          owner: 'OTR-Germany',
          repo: 'handover',
          branch: 'main',
          workflowId: 37808,
          level: 'medium',
        },
        {
          projectName: 'Handover Deploy CI',
          owner: 'OTR-Germany',
          repo: 'handover',
          branch: 'main',
          workflowId: 37809,
          level: 'medium',
        },
        {
          projectName: 'Invoices Deploy CI',
          owner: 'OTR-Germany',
          repo: 'invoices-service',
          branch: 'main',
          workflowId: 70104,
          level: 'medium',
        },
        {
          projectName: 'Performance Test',
          owner: 'OTR-Germany',
          repo: 'handover',
          branch: 'main',
          workflowId: 39231,
          level: 'medium',
        },
        {
          projectName: 'Handover Rotate App DB password',
          owner: 'OTR-Germany',
          repo: 'handover',
          branch: 'main',
          workflowId: 69492,
          level: 'medium',
        },
        {
          projectName: 'Handover Reset App DB RD password',
          owner: 'OTR-Germany',
          repo: 'handover',
          branch: 'main',
          workflowId: 69491,
          level: 'medium',
        },
        {
          projectName: 'Handover BD Full Scan',
          owner: 'OTR-Germany',
          repo: 'handover',
          branch: 'main',
          workflowId: 31337,
          level: 'medium',
        },
        {
          projectName: 'Invoices BD Full Scan',
          owner: 'OTR-Germany',
          repo: 'invoices-service',
          branch: 'main',
          workflowId: 70100,
          level: 'medium',
        },
        {
          projectName: 'PA BD Full Scan',
          owner: 'OTR-Germany',
          repo: 'pending-actions-service',
          branch: 'main',
          workflowId: 153881,
          level: 'low',
        },
        {
          projectName: 'PA Build and Deploy',
          owner: 'OTR-Germany',
          repo: 'pending-actions-service',
          branch: 'main',
          workflowId: 143183,
          level: 'high',
        },
        {
          projectName: 'PA Check and Test',
          owner: 'OTR-Germany',
          repo: 'pending-actions-service',
          branch: 'main',
          workflowId: 143184,
          level: 'low',
        },
        {
          projectName: 'PA Deploy CI',
          owner: 'OTR-Germany',
          repo: 'pending-actions-service',
          branch: 'main',
          workflowId: 143185,
          level: 'low',
        },
        {
          projectName: 'RS BD Full Scan',
          owner: 'OTR-Germany',
          repo: 'registrations-service',
          branch: 'main',
          workflowId: 153882,
          level: 'low',
        },
        {
          projectName: 'RS Build and Deploy',
          owner: 'OTR-Germany',
          repo: 'registrations-service',
          branch: 'main',
          workflowId: 141451,
          level: 'high',
        },
        {
          projectName: 'RS Check and Test',
          owner: 'OTR-Germany',
          repo: 'registrations-service',
          branch: 'main',
          workflowId: 141452,
          level: 'low',
        },
        {
          projectName: 'RS Deploy CI',
          owner: 'OTR-Germany',
          repo: 'registrations-service',
          branch: 'main',
          workflowId: 141492,
          level: 'low',
        },
      ],
    },
  },
};